import Config from 'react-native-config'

export default {
  font: {
    family: Config.FONT_FAMILY,
    sizes: {
      S: Config.FONT_SIZE_S,
      SM: Config.FONT_SIZE_SM,
      M: Config.FONT_SIZE_M,
      ML: Config.FONT_SIZE_ML,
      L: Config.FONT_SIZE_L,
      LX: Config.FONT_SIZE_LX,
      X: Config.FONT_SIZE_X,
    },
  },
  colors: {
    primary: Config.PRIMARY_COLOR,
    secondary: Config.SECONDARY_COLOR,
    textColor: Config.TEXT_COLOR,
    orangeRed: Config.ORANGE_RED_COLOR,
    tangerine: Config.TANGERINE_COLOR,
    warmBlue: Config.WARM_BLUE_COLOR,
    blue: Config.BLUE_COLOR,
    lightishPurple: Config.LIGHT_TISH_PURPLE_COLOR,
    purple: Config.PURPLE_COLOR,
    reddishPink: Config.REDDISH_PINK_COLOR,
    coolGreen: Config.COLL_GREEN_COLOR,
    skyBlue: Config.SKY_BLUE_COLOR,
    darkBlue: Config.DARK_BLUE_COLOR,
    steel: Config.STEEL_COLOR,
    lightGrey: Config.LIGHT_GREY_COLOR,
    grey: Config.GREY_COLOR,
    darkGrey: Config.DARK_GREY_COLOR,
    buttonGrey: Config.BUTTON_GREY_COLOR,
    silverTwo: Config.SILVER_TWO_COLOR,
    paleGrey: Config.PALE_GREY_COLOR,
    paleGreyTwo: Config.PALE_GREY_TWO_COLOR,
    white: Config.WHITE_COLOR,
    black: Config.BLACK_COLOR,
    red: Config.RED_COLOR,
    switeTrue: Config.PRIMARY_COLOR,
    switeFalse: Config.SWITE_FALSE_COLOR,
    subtitleGrey: Config.SUBTITLE_GREY_COLOR,
    lineGrey: Config.LINE_GREY_COLOR,
    dotLine: Config.DOT_LINE_COLOR,
    dots: Config.DOTS_COLOR,
    verticalLineGrey: Config.VERTICAL_LINE_GREY_COLOR,
    background: Config.BACKGROUND_COLOR,
    disabledGrey: Config.DISABLED_GREY_COLOR,
  },
}